### ISSUE TITLE
while deploying ospfwatcher getting error -repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by pradipsddd** [Vadims06/ospfwatcher#10]
Hi,

Could you please help me to solve below error.

⠿ logstash-index-creator Error                                                                                   1.3

Error response from daemon: pull access denied for ospfwatcher_watcher, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

[root@ospfwatcher ospfwatcher]# docker-compose up

WARN[0000] The "EXPORT_TO_ELASTICSEARCH_BOOL" variable is not set. Defaulting to a blank string.

WARN[0000] The "EXPORT_TO_ZABBIX_BOOL" variable is not set. Defaulting to a blank string.

WARN[0000] The "EXPORT_TO_WEBHOOK_URL_BOOL" variable is not set. Defaulting to a blank string.

WARN[0000] The "DEBUG_BOOL" variable is not set. Defaulting to a blank string.

WARN[0000] network internal: network.external.name is deprecated in favor of network.name

[+] Running 0/1

⠿ logstash-index-creator Error                                                                                   1.3s

Error response from daemon: pull access denied for ospfwatcher_watcher, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by Vadims06** [comment]
Hi @pradipsddd ,
Could you please make sure that you can pull images from docker hub. To check this run: `docker run hello-world` and share the output

**Comment by Vadims06** [comment]
Hi @pradipsddd ,
do you have any updates?

**Comment by eth0rob** [comment]
I am also getting this same error.

docker run hello-world works.

See below output...

root@topolograph:/home/uberadmin/tmp/ospfwatcher# docker-compose up
WARNING: The DEBUG_BOOL variable is not set. Defaulting to a blank string.
WARNING: The EXPORT_TO_ELASTICSEARCH_BOOL variable is not set. Defaulting to a blank string.
WARNING: The EXPORT_TO_ZABBIX_BOOL variable is not set. Defaulting to a blank string.
WARNING: The EXPORT_TO_WEBHOOK_URL_BOOL variable is not set. Defaulting to a blank string.
Pulling logstash-index-creator (ospfwatcher-watcher:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling logstash-index-creator (ospfwatcher-watcher:latest)...
ERROR: pull access denied for ospfwatcher-watcher, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
root@topolograph:/home/uberadmin/tmp/ospfwatcher# 
root@topolograph:/home/uberadmin/tmp/ospfwatcher# cd ..
root@topolograph:/home/uberadmin/tmp# docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
c1ec31eb5944: Pull complete 
Digest: sha256:1408fec50309afee38f3535383f5b09419e6dc0925bc69891e79d84cc4cdcec6
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

**Comment by Vadims06** [comment]
my bad, I missed `docker-compose build` line in the README on Step 7. `logstash-index-creator` is locally built image, which is needed to build one time, then start docker-compose
