### ISSUE TITLE
Error on compose up -d "pull access denied for watcher"

### ISSUE THREAD

**Issue by MLubbe8** [Vadims06/ospfwatcher#4]
Unable to pull watcher docker file even after logging in to docker.io on Debian (docker-compose) and CentOS (podman-compose) based OS. Topolograph on the other hand has no problems.

**Comment by Vadims06** [comment]
Hi @MLubbe8,
thank you for posting. I missed `docker-compose build` command in my README (fixed it). So it's needed to build firstly and then run `docker-compose up -d`. Please give me an update.

**Comment by Vadims06** [comment]
Uh, I found the issue (already fixed it), please change the docker-compose file to [this ](https://github.com/Vadims06/ospfwatcher/commit/5961955cd5f58101116cd8b28761097756959daa) and give me an update

**Comment by MLubbe8** [comment]
Thank you, it successfully pulled now!
