### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sebassur07** [Vadims06/ospfwatcher#5]
Hi, I'm having this problem when installing, could you help me please?

TKS.
--------------------------------------------------------------------------------------------------
Using bundled JDK: /usr/share/logstash/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Validating logstash-codec-csv
Installing logstash-codec-csv
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
Installation successful
Removing intermediate container c374fc1578f2
 ---> 08a70454567f
Step 4/5 : RUN logstash-plugin install logstash-output-zabbix
 ---> Running in 7894e727076b
Using bundled JDK: /usr/share/logstash/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
ERROR: File /usr/share/logstash/Gemfile does not exist or is not writable, aborting
The command '/bin/sh -c logstash-plugin install logstash-output-zabbix' returned a non-zero code: 1
ERROR: Service 'logstash' failed to build : Build failed

**Comment by Vadims06** [comment]
Hi @sebassur07 
It seems that I forgot to change default version of logstash to 7.17 in .env https://github.com/Vadims06/ospfwatcher/blob/ab889b5429f2438b4b091673dce0264a444961ea/.env#L1
