### ISSUE TITLE
Watcher in docker is restarting with error NameError: name 'lsu_obj' is not defined

### ISSUE THREAD

**Issue by ghebo** [Vadims06/ospfwatcher#6]
I'm deploying ospfwatcher stack in Docker.

Created a GRE tunnel to a Mikrotik. 

OSPF adjacency is up and running, I see full LSDB in Quagga. Although Watcher is restarting with the following error:

```
lsdb_output:
       OSPF Router with ID (172.20.0.1)


                Router Link States (Area 0.0.0.0)

  LS age: 105
  Options: 0x2  : *|-|-|-|-|-|E|-
  LS Flags: 0x6
  Flags: 0x0
  LS Type: router-LSA
  Lin
OSPF LSDB has been received
OSPF debug has been enabled
Traceback (most recent call last):
  File "/home/watcher/watcher/pytail.py", line 178, in <module>
    for lsa_obj in lsu_obj.LSA_ll:
NameError: name 'lsu_obj' is not defined

```

In OSPFWatcher GUI every time Watcher is restarted, a new saved Graph is created.

If you need any other information , I can provide.

**Comment by Vadims06** [comment]
Hi @ghebo,
Thank you for the submitting request.
This error appeared during parsing OSPF updates. Could you please send me the output from `docker exec -it quagga cat /var/log/quagga/ospfd.log` command here or on admin at topolograph.com?

**Comment by Vadims06** [comment]
Hi @ghebo ,
Let me know if you faced with any issues to get ospf logs, I will be glad to help.
