### ISSUE TITLE
Getting error code 7 while deploying Elasticsearch docker

### ISSUE THREAD

**Issue by pradipsddd** [Vadims06/ospfwatcher#9]
Hi,
we are tried to deploy OSPFWatcher on below mention OS and docker version and getting error at time of Elasticsearch

OS-AlmaLinux release 8.9 (Midnight Oncilla)
Docker-Docker version 26.0.0, build 2ae903e

root@ospfwatcher docker-elk]# docker-compose up setup
[+] Running 2/0
⠿ Container docker-elk-elasticsearch-1  Created                                                                  0.0s
⠿ Container docker-elk-setup-1          Created                                                                  0.0s
Attaching to docker-elk-setup-1
docker-elk-setup-1  | [+] Waiting for availability of Elasticsearch. This can take several minutes.
docker-elk-setup-1  |    ⠍ Failed to connect to host. Is Elasticsearch healthy?
docker-elk-setup-1 exited with code 7

could you please help to solve this any work around?

**Comment by Vadims06** [comment]
Hi @pradipsddd,
thank you for your request. I think the issue is in docker command. To start docker-compose it's needed to run `docker-compose up -d`
```
docker-elk % docker-compose up -d
WARN[0000] mount of type `volume` should not define `bind` option 
[+] Running 0/0
[+] Running 4/5er-elk_elk                Created                                                                                                                                                                 0.1s 
 ⠹ Network docker-elk_elk                Created                                                                                                                                                                 1.2s 
 ✔ Container docker-elk-elasticsearch-1  Started                                                                                                                                                                 0.6s 
 ✔ Container docker-elk-setup-1          Started                                                                                                                                                                 1.1s 
 ✔ Container docker-elk-logstash-1       Started                                                                                                                                                                 1.1s 
 ✔ Container docker-elk-kibana-1         Started
```

**Comment by maheshzagade** [comment]
I have solved this by adding the following line in elasticsearch.yml

xpack.ml.enabled: false

**Comment by maheshzagade** [comment]
On which platform this software is tested I mean Linux distribution and OS version, Docker version?
because we getting too many errors

**Comment by Vadims06** [comment]
> I have solved this by adding the following line in elasticsearch.yml
> 
> xpack.ml.enabled: false

Thank you  for sharing. I should include it in README as well. Did you still run `docker-compose up setup` to boot up ELK stack consisting of three services?.. when I tried to run it, only elasticsearch container started.

**Comment by Vadims06** [comment]
> On which platform this software is tested I mean Linux distribution and OS version, Docker version? because we getting too many errors

I used Ubuntu 20.04 Linux for my setup.
Feel free to share your experience to setup it. We can update README appropriately and make it better.
